version: '3'
services:
    php:
        image: 'webdevops/php-nginx-dev:8.2-alpine'
        working_dir: /var/www
        ports:
            - '80:80'
            - '443:443'
        volumes:
            - ./:/var/www
            - ./docker/nginx.conf:/opt/docker/etc/nginx/vhost.conf
            - ./docker/scheduler.sh:/opt/docker/bin/service.d/cron.d/scheduler.sh
        networks:
            - app_network
        depends_on:
            - mysql

    npm:
        image: 'node:18-alpine'
        working_dir: /var/www
        ports:
            - '${VITE_PORT:-5173}:5173'
        volumes:
            - ./:/var/www
        networks:
            - app_network
        depends_on:
            - php
        command: sh -c "npm install && npm run dev"

    mysql:
        image: 'mysql/mysql-server:8.0'
        ports:
            - '${DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - 'mysql_storage:/var/lib/mysql'
        networks:
            - app_network
        healthcheck:
            test: [ 'CMD', 'mysqladmin', 'ping', '-p${DB_PASSWORD}' ]
            retries: 3
            timeout: 5s

    phpmyadmin:
        image: 'phpmyadmin/phpmyadmin'
        links:
            - mysql:mysql
        ports:
            - '${PMA_PORT:-8080}:80'
        environment:
            PMA_HOST: mysql
            MYSQL_USERNAME: '${DB_USERNAME}'
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            PMA_USER: '${DB_USERNAME}'
            PMA_PASSWORD: '${DB_PASSWORD}'
        networks:
            - app_network

    mailpit:
        image: 'axllent/mailpit:latest'
        ports:
            - '${MAIL_PORT:-1025}:1025'
            - '${MAIL_DASHBOARD_PORT:-8025}:8025'
        networks:
            - app_network

networks:
    app_network:
        driver: bridge

volumes:
    mysql_storage:
        driver: local
